http:
  basePath: "/api/v1/*"
  host: "0.0.0.0"
  private:
    port: "8091"
  consolePath: "/console/*"

#----Common Block---No change Needed----      
cloudhub:
  username: "![5/w01nYmhxyvgHVC8Uh0yvTYk/WLHWBP2ZU+9DMOSnw=]"
  password: "![ae5QSfiTACKaB08EZlg0AA==]"
  
smtp:
  host: "mail.fatface.net"
  port: "465"
  user: "![5/w01nYmhxyvgHVC8Uh0yvTYk/WLHWBP2ZU+9DMOSnw=]"
  password: "![ae5QSfiTACKaB08EZlg0AA==]"
  subject: "Fatface API Exception"
#----Common Block---No change Needed----

api:
  discovery:
    id: ""

db:
 audit: 
  config:
   host: "mule-sandbox.cm1i2vsjtzdf.eu-west-1.rds.amazonaws.com"
   port: "1433"
   user: "![AyD0mBi0zwPqptV8KbEJGkjzeMuTdVHL2AEWiq0N3sQ=]"
   password: "![PX91DJD02zpJ0MJ3jLRKUw==]"
   database: "FATFACE_DB" 

sftp:
  host: "ftp.fatface.com"
  port: "22"
  username: "![W49cMbSedB3HHfPcr0pWWyYHk27r5mLh++/a62Nglxg=]"
  password: "![YoKYhq6QWsR9eW3AVcCh2TRSSvrwrp94baroSAHlBlg=]" 
  
sqs:
  accessKey: "![iKDP0/LYfR1ghGUCOAayKYI5kMT/ieTr3IMibNfn9y8=]"
  secretKey: "![z8W9r4EBG78ATEDLlzRgrDu8pSr3cf8u0RPGoG/mEyLZSeyc1prL/JqYzbF2CWUY]"
  region: "![6lleIG6Qoif/fTA7pK+sUA==]"
        
d365:
  host: "mule-worker-internal-s-d365-api.ir-e1.cloudhub.io"
  port: "8091"
  basePath: "/api/v1"
  path: "/stores"
  client_id: "587f052383c44efbadc76e22201cba19"
  client_secret: "![+6LrbmEe+njbAiXUXZX1+7Nq1IMTLZTmBBLwyUF89jr5yQxXx6ydvM5v0UczJCgE]"
  dmf:
    path: "/dmf/export"
  store:
    definitionGroupId: "IDD022-RetailStoreIntegration-Export"
    packageName: "Store-Data-"
  
demandware:
  host: "s-dw-data-int.ir-e1.cloudhub.io"
  port: "443"
  basePath: "/api/v1"
  path: "/store"
  client_id: "587f052383c44efbadc76e22201cba19"
  client_secret: "![+6LrbmEe+njbAiXUXZX1+7Nq1IMTLZTmBBLwyUF89jr5yQxXx6ydvM5v0UczJCgE]"
  
response:
  timeout: "120000"
  
scheduler:
  cron:
    expression: "0 30 16 1/1 * ? *"
    fixed: "10"
    
client:
  keystore:
    password: "![Eiy80pOc3NMdDEvvqf5eTmUuYTIchkvpv2kk4Ge7Xv8=]"

status:
  responsecode: "200"
  responsemessage: "Success"
  
lookup:
  host: "mule-worker-internal-prod-s-dblookup-api.ir-e1.cloudhub.io"
  port: "8091"
  basePath: "/api/v1"
  dbLookupPath: "/lookups"
  key: "COUNTRY_CODES-ALPHA-3-D365"
  clientId: "587f052383c44efbadc76e22201cba19"
  clientSecret: "![+6LrbmEe+njbAiXUXZX1+7Nq1IMTLZTmBBLwyUF89jr5yQxXx6ydvM5v0UczJCgE]"
  queryParam:
    type: "COUNTRY_CODES"
    category: "ALPHA-3"
    source: "D365"      