#%RAML 1.0 Library
usage: |
 library of datatypes to form domain driven model (Bounded Context) to be used by concerned APIs

types:
  sample: !include dataTypes//sample.raml #this is for template reference
  samples: 
    type: array
    items: !include dataTypes//sample.raml
  products: 
    type: array
    items: !include dataTypes//product.raml
  pick-orders:
    type: array
    items: !include dataTypes//order.raml  
  stores:
    type: array
    items: !include dataTypes//store.raml
  warehouses:
    type: array
    items: !include dataTypes//warehouse.raml
  manifests:
    type: array
    items: !include dataTypes//manifest.raml
  orders:
    type: array
    items: !include dataTypes//order.raml
  inventories:
    type: array
    items: !include dataTypes//inventory.raml
  store-inventories:
    type: array
    items: !include dataTypes//store-inventory.raml
  web-inventories:
    type: array
    items: !include dataTypes//web-inventory.raml
  sales-orders:
    type: array
    items: !include dataTypes//sales-order.raml
  lookup-data:
     type: array
     items: !include dataTypes//lookup.raml  