#%RAML 1.0 NamedExample
"order-no": "UKF4100007910"
"currency": "GBP"
"invoice-amount": "58.45"
"order-type": "Sales"
"sales-pool": "SFCC"
"sales-status": "Invoiced"
"transaction-id": "b1829ca5-71fb-42e0-9864-140d4ffb925a"
"orderlines" : [!include order-line.raml]
"shipments": [!include shipment.raml]