#%RAML 1.0 NamedExample
- package-id: "A"
  tracking-number: "7855715164"
  package-tracking-url: "https://www.dhl.co.uk/en/express/tracking.html?AWB=7855715164&brand=DHL"
- package-id: "B"
  tracking-number: "7875795169"
  package-tracking-url: "https://www.dhl.co.uk/en/express/tracking.html?AWB=7875795169&brand=DHL"