#%RAML 1.0 NamedExample
quantity: 1.0
barcode: "505275155067"
sales-price: 39.6
item-name: "LEA LINEN BLEND DRESS"
item-id: "939007"
amount: 40.8
line-id: 1
created-date: 2015-07-04T21:00:00
modified-date: 2015-08-10T07:00:00
invent-trans-id: "1111"
cancelled-quantity: 0.000000
delivered-quantity: 0.000000
delivery-remainder: 1.000000
invoice-remainder: 0.000000
item-group-id: "Finished"
tax-amount: 0.000000
ordered-quantity: 1
return-status: "None"
product: !include sales-product.raml
warehouse: !include warehouse.raml
promotions: [!include promotion.raml]