#%RAML 1.0 NamedExample
order-no: "28759577"
currency: "GBP"
net-amount: 39.6
modified-date: 2015-07-04T21:00:00
order-type: "Return order"
orginal-sales-order-id: "121212"
pool: "pool"
return-status: "closed"
rma-no: "12121"
source: "Ecommerce"
sales-status: "Open order"
vat-amount: 0.0000003
transaction-id: "d2f4d760-c41f-42d1-b87f-3d8fd8fe6487"
orderlines: [!include sales-orderline.raml]