#%RAML 1.0 NamedExample
store-id: "000013"
name: "505275086776"
store-address: !include store-address.raml
click-and-collect: true
store-fulfillment: true
longitude: "1273849"
latitude: "1273849"
monday-open-time: 10:00:00
monday-close-time: 17:00:00
tuesday-open-time: 10:00:00
tuesday-close-time: 17:00:00
wednesday-open-time: 10:00:00
wednesday-close-time: 17:00:00
thursday-open-time: 10:00:00
thursday-close-time: 17:00:00
friday-open-time: 10:00:00
friday-close-time: 12:30:00
saturday-open-time: 10:00:00
saturday-close-time: 17:00:00
sunday-open-time: 10:00:00
sunday-close-time: 17:00:00