#%RAML 1.0 DataType
type: object
displayName: manifest
properties:
  route-id?: string
  item-id?: string
  barcode?: string
  carrier-consignment-id?: string
  container-id?: string
  site-id?: string
  location-id?: string
  quantity?: number
  shipping-date?: datetime-only
  order-no?: string
  carrier-id?: string
  status?: string