#%RAML 1.0 DataType
type: object
displayName: payment mode card type
properties:
  card-type?: string
  card-number?: string
  card-holder?: string
  card-token?: string
  expires-month?: string
  expires-year?: string