#%RAML 1.0 DataType
type: object
displayName: totals
properties:
  adjusted-merchandize-total?: !include adjusted-merchandize-total.raml
  merchandize-total?: !include merchandize-total.raml
  shipping-total?: !include shipping-total.raml
  adjusted-shipping-total?: !include adjusted-shipping-total.raml
  shippment-total?: !include shippment-total.raml