#%RAML 1.0 DataType
type: object
displayName: address
properties:
  first-name?: string
  second-name?: string 
  last-name?: string
  full-name?: string
  address-id?: string
  address-1?: string
  address-2?: string
  suite?: string
  city?: string
  town?: string
  postcode?: string
  county?: string
  country?: string
  street?: string
  state?: string
  contact-number?: string
  description?: string
   