#%RAML 1.0 DataType
type: object
displayName: option line item
properties:
  product-id?: string
  tax?: number
  gross-price?: number
  base-price?: number
  net-price?: number
  line-item-text?: string
  tax-basis?: number
  position?: number
  quantity-unit?: number
  tax-rate?: number
  min-order-quantity?: number
  step-quantity?: number
  brand?: string
  shipment-id?: string
  personalize-text? : string
  personalize-text-color? : string
  price-adjustments?: 
    displayName: price adjustment details
    type: array
    items: !include price-adjustment.raml
 