#%RAML 1.0 DataType
type: object
displayName: Ware house
properties:
  warehouse-id?: string
  name?: string
  email?: string
  warehouse-address?:
    type: !include address.raml
  products?:
    displayName: List of products
    type: array
    items: !include product.raml