#%RAML 1.0 DataType
type: object
displayName: customer
properties:
  customer-id?: string
  salutation?: string
  fullname?: string
  first-name?: string
  second-name?: string
  last-name?: string
  suffix?: string
  telephone?: string
  mobile?: string
  email?: string
  fax?: string
  company-name?: string
  job-title?: string
  shipping-address?:
    type: !include address.raml
  billing-address?:
    type: !include address.raml  
