#%RAML 1.0 DataType
type: object
displayName: price adjustment
properties:
  promotion-id?: string
  campaign-id?: string
  discount?: !include discount.raml
  net-price?: number
  lineitem-text?: string
  tax-basis?: number
  tax?: number
  base-price?: number