#%RAML 1.0 DataType
type: object
displayName: shipping-consignment-report
properties:
  shipping-consignment?: !include shipping-consignment.raml
  status?: string
  error-code?: string
  error-description?: string