#%RAML 1.0 DataType
type: object
displayName: sku
properties:
  colour?: string
  barcode?: string
  check-digit?: string
  size?: string
  fit?: string
  quantity?: string
  disposition-code?: string
  base-price?: number